### ISSUE TITLE
Generate build info file (SBOM)

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-build-tools#62]
Generate a file stating build infos about an app build, e.g.:
- build date
- used packages and their versions
- (git revision) 

The file does not need to be included in the directory that is used for deployment on a server but can be stored at the same level or together with other information (e.g. license files). 

**Use case**: 
Such a file states information that are useful if one wants to know about build details later on. This is especially useful when delivering a build app to a customer. Given an SBOM, one can check software licenses and scan for security vulnerabilities.

Implementation idea: 
Use SBOM format (e.g. cycloneDX) and tooling. 

[Trivy](https://aquasecurity.github.io/trivy/v0.33/docs/sbom/cyclonedx/) looks good and supports pnpm.

```bash
$ trivy fs -f cyclonedx .
```

**Comment by mbeckem** [comment]
PR: #108
